### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by kw054** [timospringer/clarovo#3]
Hey Leute, 

hab mal bisschen nach dem Ganzen QR Code Zeug gegooglet. 
Hab natürlich tausende Seiten gefunden. Die Beste wie mir scheint ist die hier. 

http://phpqrcode.sourceforge.net/

Versteh nur nich ganz wie man hier die PHP Library includieren kann wenn man die Datei nicht hat. Oder versteh ich da gerade was nicht richtig? 

Habe auch oft nur gesehen, dass man von Hand eingeben muss auf welche Seite verlinkt werden soll. Wir bräuchten das ganze aber dynamisch, dass es automatisch geht. Jemand dazu eine Idee? 

Grüße

**Comment by timospringer** [comment]
Hey Kev(in),

kann man die vielleicht irgendwo runterladen?
Also man kann sowas auch über den Link einbinden. Kann ich dir mal zeigen :)

Gruß Timo
